version: '3.9'

networks:
  bet_on_you_network: {}

services:
  bet_on_you:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bet_on_you
    container_name: bet_on_you
    ports:
      - 8080:5000
    networks:
      - bet_on_you_network
    volumes:
     - ./src/:/app
     - ./instance/:/app/instance
    command: flask run --host=0.0.0.0

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - bet_on_you_network
    environment:
      MYSQL_ROOT_PASSWORD: root
